name: masaratapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
# ----------------------------------------
  flutter_localizations: ##to support arabic lacal in date picker and month picker
    sdk: flutter         ##
   
  intl:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.4.0
  shimmer: ^3.0.0
   # sqflite------------------------
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
    # start of the app -------------
  flutter_launcher_icons: ^0.14.3
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.4
  # ------------------------------
  pluto_grid: ^8.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_datepicker: ^29.1.38
  open_file: ^3.5.10
  flutter_svg: ^2.1.0
  share_plus: ^11.0.0
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  # zerotier_sockets: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


# how to use:
# flutter pub get
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "pos_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:   
   - assets/images/
  #  - assets/images/primaryBg.png
  #  - assets/images/logo.ico

  fonts:
  - family: Arial
    fonts:
      - asset: assets/fonts/Arial.ttf
  # - family: CairoPlay
  #   fonts:
  #     - asset: assets/fonts/CairoPlay-SemiBold.ttf
  #     - asset: assets/fonts/CairoPlay-Regular.ttf
  #     - asset: assets/fonts/CairoPlay-Bold.ttf
  # - family: Cairo
  #   fonts:
  #     - asset: assets/fonts/Cairo-SemiBold.ttf
  #     - asset: assets/fonts/Cairo-Regular.ttf
  #     - asset: assets/fonts/Cairo-Bold.ttf
  # - family: Amiri
  #   fonts:
  #     - asset: assets/fonts/Amiri-Italic.ttf
  #     - asset: assets/fonts/Amiri-Regular.ttf
  #     - asset: assets/fonts/Amiri-Bold.ttf

  
#Run CMD to generate Splash screen
#1) flutter clean
#2) flutter pub get
#3) flutter pub run flutter_native_splash:create

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#203e5a"

