name: masaratapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
# ----------------------------------------
  flutter_localizations: ##to support arabic lacal in date picker and month picker
    sdk: flutter         ##
   
  intl:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.4.0
  shimmer: ^3.0.0
   # sqflite------------------------
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
    # start of the app -------------
  flutter_launcher_icons: ^0.14.3
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.4
  # ------------------------------
  pluto_grid: ^8.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_datepicker: ^29.1.38
  open_file: ^3.5.10
  flutter_svg: ^2.1.0
  share_plus: ^11.0.0
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1  
  # zerotier_sockets: ^1.1.0

  #------------MAP--
  # 
  flutter_map: ^8.2.2
  flutter_map_marker_popup: ^8.1.0
  geolocator: 9.0.2
  flutter_map_animations: ^0.9.0
  latlong2: ^0.9.1
  # huawei_location: ^6.16.0+300




# MANAR app dependices
  # # The following adds the Cupertino Icons font to your application.
  # # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2
  # http: ^1.1.0
  # flutter_locales: ^3.0.1
  # month_picker_dialog: ^2.7.0
  # # syncfusion_flutter_datagrid: ^24.2.9
  # syncfusion_flutter_charts: ^24.2.9
  # animated_digit: ^3.2.3

  # # syncfusion_flutter_core: any
  # intl: any
  # syncfusion_flutter_datagrid_export: ^24.2.9
  # # syncfusion_flutter_pdf: ^24.2.9
  # path_provider: ^2.1.3
  # file_picker: ^8.0.3
  # permission_handler: ^11.3.1
  # open_file: ^3.3.2
  # internet_connection_checker_plus: ^2.2.0
  # syncfusion_flutter_datepicker: ^24.2.9
  # # flutter_speed_dial: ^7.0.0
  # badges: ^3.1.1
  # pluto_grid_plus: ^8.4.0
  # excel: ^4.0.3
  # pdf: ^3.10.89
  # # draggable_home: ^1.0.5
  # # another_flushbar: ^1.12.30
  # # fl_chart: ^0.68.0
  # provider: ^6.1.2
  # google_maps_flutter: ^2.2.8  #####
  # # custom_map_markers: ^0.0.2+1
  # google_maps_flutter_web: ^0.5.8 ####
  # flutter_map: ^7.0.2
  # flutter_map_marker_popup: ^7.0.0
  # url_launcher: ^6.3.0
  # # dio: ^5.6.0
  # font_awesome_flutter: ^10.7.0
  # # parent_child_checkbox: ^0.0.5
  # google_fonts: ^6.1.0
  # webview_flutter: ^4.8.0
  # flutter_dotenv: ^5.2.1
  # universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


# how to use:
# flutter pub get
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "pos_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:   
   - assets/images/
  #  - assets/images/primaryBg.png
  #  - assets/images/logo.ico

  fonts:
  - family: Arial
    fonts:
      - asset: assets/fonts/Arial.ttf
  # - family: CairoPlay
  #   fonts:
  #     - asset: assets/fonts/CairoPlay-SemiBold.ttf
  #     - asset: assets/fonts/CairoPlay-Regular.ttf
  #     - asset: assets/fonts/CairoPlay-Bold.ttf
  # - family: Cairo
  #   fonts:
  #     - asset: assets/fonts/Cairo-SemiBold.ttf
  #     - asset: assets/fonts/Cairo-Regular.ttf
  #     - asset: assets/fonts/Cairo-Bold.ttf
  # - family: Amiri
  #   fonts:
  #     - asset: assets/fonts/Amiri-Italic.ttf
  #     - asset: assets/fonts/Amiri-Regular.ttf
  #     - asset: assets/fonts/Amiri-Bold.ttf

  
#Run CMD to generate Splash screen
#1) flutter clean
#2) flutter pub get
#3) flutter pub run flutter_native_splash:create

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#203e5a"

